server:
  port: 2000
spring:
  application:
    name: service-user
  datasource:
    url: jdbc:mysq://localhost:3306/java1;
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
eureka:
  client:
    service-url:
      default-zone: http://127.0.0.1:1000/eureka/